trigger:
  branches:
    include:
      - dev

pr: none

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
- template: ../variables/common.yml

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- template: ../../docs/templates/PRs/auto-pr-chain.yml
  parameters:
    adoOrg: 'tcrowe0170'
    adoProject: 'DataImportExportManager'
    repositoryId: 'DataImportExportManager'
    sourceBranch: 'dev'
    targetBranch: 'main'
